name: Screen
on: [push, pull_request]

defaults:
  run:
    working-directory: .github/workflows/screen

jobs:
  screen:
    name: Screen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node16-screen-${{ hashFiles('package-lock.json') }}

      - name: Screen dependencies
        run: node ./index.js
